"""
  DHT event constants
"""
DHT_EVENT_ERROR = -1
DHT_EVENT_SETUP_DONE = 0
DHT_EVENT_LOOKUP_DONE = 1
DHT_EVENT_ANNOUNCE_DONE = 2
DHT_EVENT_VALUES = 3
DHT_EVENT_GET_DONE = 4
DHT_EVENT_PUT_DONE = 5
DHT_EVENT_VALUE_ITEM = 6
